# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Use a Node.js image as the base
FROM node:18-alpine AS builder

# Set the working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY package.json package-lock.json ./

# Install dependencies
RUN npm install

# Copy the rest of the source code
COPY . .

# Build the TypeScript files
RUN npm run build

# Use a lightweight Node.js image for production
FROM node:18-alpine

# Set the working directory
WORKDIR /app

# Copy only the build files and package files
COPY --from=builder /app/build /app/build
COPY --from=builder /app/package.json /app/package.json
COPY --from=builder /app/package-lock.json /app/package-lock.json

# Install only production dependencies
RUN npm ci --omit=dev

# Set the environment variable for the API key
ENV PERPLEXITY_API_KEY=YOUR_API_KEY_HERE

# Start the server
CMD ["node", "build/index.js"]
